### ISSUE TITLE
Build with esp-idf V5.4

### ISSUE THREAD

**Issue by nopnop2002** [martin-ger/esp_wifi_repeater#560]
When I build with esp-idf V5.4, I got this error.
```
Compilation failed because cmd_router.c (in "cmd_router" component) includes spi_flash_mmap.h, provided by spi_flash component(s).
However, spi_flash component(s) is not in the requirements list of "cmd_router".
To fix this, add spi_flash to PRIV_REQUIRES list of idf_component_register call in /home/nop/esp32_nat_router/components/cmd_router/CMakeLists.txt.
```

So i changed components/cmd_router/CMakeLists.txt.
```
idf_component_register(SRCS "cmd_router.c"
                    INCLUDE_DIRS .
                    REQUIRES console nvs_flash esp_wifi driver spi_flash)
```

We can build with esp-idf V5.4.
