### ISSUE TITLE
OTAUPDATE 0 produce an error

### ISSUE THREAD

**Issue by Azuxul** [martin-ger/esp_wifi_repeater#263]
Hello,

When i try to build (make) with OTAUPDATE define to 0, i got an error : 

> CC user/rboot-ota.c
> user/rboot-ota.c: In function 'upgrade_connect_cb':
> user/rboot-ota.c:224:9: error: 'sysconfig_t' has no member named 'ota_host'
>    config.ota_host, HTTP_HEADER);
>          ^
> In file included from /usr/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/include/arch/cc.h:40:0,
>                  from /usr/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/include/lwip/arch.h:43,
>                  from /usr/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/include/lwip/debug.h:35,
>                  from include/lwip/opt.h:46,
>                  from /usr/esp-open-sdk/xtensa-lx106-elf/xtensa-lx106-elf/sysroot/usr/include/lwip/ip_addr.h:35,
>                  from /usr/wifi/../esp-open-sdk/sdk/include/user_interface.h:30,
>                  from user/rboot-ota.c:10:
> user/rboot-ota.c: In function 'upgrade_resolved':
> user/rboot-ota.c:282:52: error: 'sysconfig_t' has no member named 'ota_host'
>    os_printf("DNS lookup failed for: %s\r\n", config.ota_host);
>                                                     ^
> user/rboot-ota.c:295:48: error: 'sysconfig_t' has no member named 'ota_port'
>   upgrade->conn->proto.tcp->remote_port = config.ota_port;
>                                                 ^
> user/rboot-ota.c: In function 'rboot_ota_start':
> user/rboot-ota.c:365:54: error: 'sysconfig_t' has no member named 'ota_host'
>   result = espconn_gethostbyname(upgrade->conn, config.ota_host, &upgrade->ip, upgrade_resolved);
>                                                       ^
> Makefile:172: recipe for target 'build/user/rboot-ota.o' failed
> make: *** [build/user/rboot-ota.o] Error 1

Build on Ubuntu 16.04.5 LTS (W10 support) with SDK 2.1.0-18-g61248df.

**Comment by martin-ger** [comment]
Thanks for the report. Should be fixed with latest push.
